[package]
name = "floorplan-3d-model-generator"
version = "0.1.0"
authors = ["Jonas Liljestrand <jonas.liljestrand@gmail.com>"]
edition = "2018"

[dependencies]
immense = "*"
serde_json = "*"
serde = { version = "*", features = ["derive"] }
